from __future__ import annotations

import asyncio
from dataclasses import asdict
from typing import Literal

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field

from src.matching_engine import MatchingEngine, Trade
from src.order import Order, Side

app = FastAPI(
    title="In-Memory Order Book API",
    description="REST API for submitting orders to an in-memory price-time priority matching engine.",
    version="1.0.0",
)

engine = MatchingEngine()
engine_lock = asyncio.Lock()
trade_history: list[Trade] = []


def reset_engine_state() -> None:
    """Reset in-memory state. Intended for tests and local development only."""
    global engine
    engine = MatchingEngine()
    trade_history.clear()


class OrderRequest(BaseModel):
    side: Literal["buy", "sell"]
    price: float = Field(..., gt=0, description="Limit price for the order")
    quantity: int = Field(..., gt=0, description="Order quantity")


class TradeResponse(BaseModel):
    buy_order_id: str
    sell_order_id: str
    price: float
    quantity: int


class OrderResponse(BaseModel):
    order_id: str
    side: str
    price: float
    remaining_quantity: int
    status: str
    trades: list[TradeResponse]


class BookLevel(BaseModel):
    order_id: str
    price: float
    quantity: int
    timestamp: float


class OrderBookResponse(BaseModel):
    top_of_book: dict
    bids: list[BookLevel]
    asks: list[BookLevel]


@app.get("/health")
def health_check() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/orders", response_model=OrderResponse, status_code=201)
async def submit_order(order_request: OrderRequest) -> OrderResponse:
    """Submit a limit order into the in-memory matching engine."""
    try:
        order = Order(
            side=Side(order_request.side),
            price=order_request.price,
            quantity=order_request.quantity,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    async with engine_lock:
        trades = engine.submit_order(order)
        trade_history.extend(trades)

    status = "filled" if order.quantity == 0 else "open"

    return OrderResponse(
        order_id=order.order_id,
        side=order.side.value,
        price=order.price,
        remaining_quantity=order.quantity,
        status=status,
        trades=[TradeResponse(**asdict(trade)) for trade in trades],
    )


@app.get("/orderbook", response_model=OrderBookResponse)
async def get_order_book(depth: int = Query(default=10, ge=1, le=100)) -> OrderBookResponse:
    """Return top-of-book plus current bid/ask levels from the in-memory book."""
    async with engine_lock:
        bids = sorted(engine.order_book.bids)[:depth]
        asks = sorted(engine.order_book.asks)[:depth]
        top_of_book = engine.top_of_book()

    return OrderBookResponse(
        top_of_book=top_of_book,
        bids=[BookLevel(order_id=o.order_id, price=o.price, quantity=o.quantity, timestamp=o.timestamp) for o in bids],
        asks=[BookLevel(order_id=o.order_id, price=o.price, quantity=o.quantity, timestamp=o.timestamp) for o in asks],
    )


@app.get("/trades", response_model=list[TradeResponse])
async def get_trades(limit: int = Query(default=50, ge=1, le=500)) -> list[TradeResponse]:
    """Return recent trades generated by matched orders."""
    async with engine_lock:
        recent_trades = trade_history[-limit:]

    return [TradeResponse(**asdict(trade)) for trade in recent_trades]
